name: Deploy to EC2

on:
  release:
    types: [published]
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Run Build
        run: ./gradlew clean -Pprod build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: extract_version
        run: |
          FILENAME=$(basename build/libs/demo-*.jar)
          VERSION=$(echo "$FILENAME" | sed -E 's/demo-([0-9.]+)\.jar/\1/')
          echo "Extracted version: $VERSION"
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: push_image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.extract_version.outputs.version }}
          labels: version=${{ steps.extract_version.outputs.version }}
