name: Deploy DEV

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Get latest Tag
        id: latest-tags
        run: |
          git fetch -a
          echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
      - name: Build and deploy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo $LATEST_TAG
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
          docker build --build-arg VERSION=$LATEST_TAG -t $ECR_REGISTRY/$REPO_NAME:$GITHUB_SHA -t $ECR_REGISTRY/$REPO_NAME:latest .
          docker push -a $ECR_REGISTRY/$REPO_NAME
          aws ecs update-service --cluster example --service $REPO_NAME --task-definition $REPO_NAME --force-new-deployment
